export const allProductsJSON = [
  {
    id: 1,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/memory/ADDX1600W8G.avif`,
    name: "ADATA RAM 8GB DDR3-1600 PC UDIMM",
    brand: "NsxGamers",
    price: "58.90",
    prevPrice: "88.90",
    sale: "sale"
  },
  {
    id: 2,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Motherboard",
    img: `${process.env.PUBLIC_URL}/img/motherboard/900MB1BX0-MOE.webp`,
    name: "Gaming PC Intel (Intel Core I5 12400F, 16 GB RAM, RTX 3060, SSD NVME of 1tb, Peripherals)",
    brand: "NsxGamers",
    price: "650",
    prevPrice: "999",
    sale: "sale"
  },
  {
    id: 3,
    collection: "yes",
    gaming: "yes",
    office: "no",
    components: "no",
    peripheral: "no",
    category: "PC Gaming",
    img: `${process.env.PUBLIC_URL}/img/gaming/Disenosintitulo_2.webp`,
    name: "ASUS Gaming PC - CES 2023 - AMD Ryzen 9 7950X, RTX STRIX GEFORCE GTX 4080, RAM 32GB",
    brand: "NsxGamers",
    price: "4379",
    prevPrice: "7599",
    sale: "sold out"
  },
  {
    id: 4,
    collection: "yes",
    gaming: "yes",
    office: "no",
    components: "no",
    peripheral: "no",
    category: "PC Gaming",
    img: `${process.env.PUBLIC_URL}/img/nsx2.webp`,
    name: "AMD Xtreme Gaming PC (Ryzen 7 5700X, 32 GB RAM, RTX 3070 Ventus 2X, Liquid Cooler, Peripherals)",
    brand: "NsxGamers",
    price: "1849",
    prevPrice: "2219",
    sale: "sale"
  },
  {
    id: 5,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Motherboard",
    img: `${process.env.PUBLIC_URL}/img/motherboard/90MB1950-M0E.webp`,
    name: "Asus Prime B660M-K D4 Intel LGA 1700 Micro ATX DDR4 Motherboard (OPEN BOX)",
    brand: "NsxGamers",
    price: "135",
    prevPrice: "599",
    sale: "sale"
  },
  {
    id: 6,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Motherboard",
    img: `${process.env.PUBLIC_URL}/img/gaming/Disenosintitulo_2.webp`,
    name: "ASUS Gaming PC - CES 2023 - AMD Ryzen 9 7950X, RTX STRIX GEFORCE GTX 4080, RAM 32GB",
    brand: "NsxGamers",
    price: "4379",
    prevPrice: "7599",
    sale: "sold out"
  },
  {
    id: 7,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Motherboard",
    img: `${process.env.PUBLIC_URL}/img/motherboard/900MB18E0-MOE.webp`,
    name: "Asus ROG Maximus Z690 Hero LGA 1700 Intel ATX DDR5 Motherboard 90MB18E0-M0EAY0",
    brand: "NsxGamers",
    price: "630",
    prevPrice: "799",
    sale: "sale"
  },
  {
    id: 8,
    collection: "yes",
    gaming: "no",
    office: "yes",
    components: "no",
    peripheral: "no",
    category: "Office",
    img: `${process.env.PUBLIC_URL}/img/office/306-7G16X21.jpg`,
    name: "CASE MSI MAG FORGE 111R ATX",
    brand: "NsxGamers",
    price: "85",
    prevPrice: "99",
    sale: "sale"
  },
  {
    id: 9,
    collection: "yes",
    gaming: "yes",
    office: "no",
    components: "no",
    peripheral: "no",
    category: "components",
    img: `${process.env.PUBLIC_URL}/img/components/Disenosintitulo.webp`,
    name: "COOLERMASTER Gaming PC - CES 2023 - AMD Ryzen 9 7950X, Radeon™ RX 6950 XT, RAM 32GB",
    brand: "NsxGamers",
    price: "3219",
    prevPrice: "7599",
    sale: "sold out"
  },
  {
    id: 10,
    collection: "yes",
    gaming: "yes",
    office: "no",
    components: "no",
    peripheral: "no",
    category: "PC Gaming",
    img: `${process.env.PUBLIC_URL}/img/gaming/COOLERMASTERGamingPC.webp`,
    name: "COOLERMASTER Gaming PC - CES 2023 - Intel Core i9 13900K, GeForce RTX® 4090 SUPRIM, RAM 32 GB",
    brand: "NsxGamers",
    price: "4279",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 11,
    collection: "yes",
    gaming: "yes",
    office: "no",
    components: "no",
    peripheral: "no",
    category: "PC Gaming",
    img: `${process.env.PUBLIC_URL}/img/gaming/B3A65FCA-7993-42F0-80C3-A092E3C34F47.webp`,
    name: "CORSAIR Gaming Computer - CES 2023 - AMD Ryzen 7 5800X, GeForce RTX® 3070, RAM 32GB",
    brand: "NsxGamers",
    price: "3169",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 12,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "no",
    peripheral: "yes",
    category: "Headset",
    img: `${process.env.PUBLIC_URL}/img/peripherals/CA-9011225-N_59a130b7-ece4-4794-a236-23345875a8ab.webp`,
    name: "Corsair Gaming Headset HS60 HAPTIC CARBON",
    brand: "NsxGamers",
    price: "127",
    prevPrice: "180",
    sale: "sale"
  },
  {
    id: 13,
    collection: "yes",
    gaming: "yes",
    office: "no",
    components: "no",
    peripheral: "no",
    category: "PC Gaming",
    img: `${process.env.PUBLIC_URL}/img/gaming/E2180064-7FE0-41B0-8216-4EA325389976.webp`,
    name: "CORSAIR Gaming PC - CES 2023 - Intel Core i9 11900K, GeForce RTX® 3070, RAM 32GB",
    brand: "NsxGamers",
    price: "2969",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 14,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "no",
    peripheral: "yes",
    category: "Headset",
    img: `${process.env.PUBLIC_URL}/img/peripherals/CA-9011198-N.webp`,
    name: "Corsair HS35 - Stereo Gaming Headset - Discord Certified - Memory Foam Earcups - Red",
    brand: "NsxGamers",
    price: "50",
    prevPrice: "95",
    sale: "sale"
  },
  {
    id: 15,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "no",
    peripheral: "yes",
    category: "Headset",
    img: `${process.env.PUBLIC_URL}/img/peripherals/CA-9011197-N.webp`,
    name: "Corsair HS35 - Stereo Gaming Headset - Memory Foam Earcups - Discord Certified- Green",
    brand: "NsxGamers",
    price: "50",
    prevPrice: "95",
    sale: "sale"
  },
  {
    id: 16,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "no",
    peripheral: "yes",
    category: "Headset",
    img: `${process.env.PUBLIC_URL}/img/peripherals/CA-9011196-N.webp`,
    name: "Corsair HS35 - Stereo Gaming Headset - Memory Foam Earcups - Discord Certified– Blue",
    brand: "NsxGamers",
    price: "53",
    prevPrice: "95",
    sale: "sale"
  },
  {
    id: 17,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "no",
    peripheral: "yes",
    category: "Headset",
    img: `${process.env.PUBLIC_URL}/img/peripherals/CA-9011225-N.webp`,
    name: "Corsair HS60 HAPTIC Stereo Gaming Headset with Haptic Bass, Carbon",
    brand: "NsxGamers",
    price: "127",
    prevPrice: "195",
    sale: "sale"
  },
  {
    id: 18,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Power Supply",
    img: `${process.env.PUBLIC_URL}/img/components/D955EECE-418D-487E-8844-1BCE7CF1609F.webp`,
    name: "EVGA 700 BR, 80+ Bronze 700W, 3 Year Warranty, Power Supply",
    brand: "NsxGamers",
    price: "83",
    prevPrice: "95",
    sale: "sold out"
  },
  {
    id: 19,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "GPU",
    img: `${process.env.PUBLIC_URL}/img/components/16321D5F-4F24-409F-940F-0B418C928D73.webp`,
    name: "EVGA GeForce RTX 3080 (12GB FTW3 Ultra Gaming,12GB GDDR6X, iCX3 Technology, ARGB LED, Metal Backplate, LHR)",
    brand: "NsxGamers",
    price: "1099",
    prevPrice: "2599",
    sale: "sold out"
  },
  {
    id: 20,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Power Supply",
    img: `${process.env.PUBLIC_URL}/img/components/71N51oVldTL._AC_SL1500.webp`,
    name: "EVGA V1 650 GQ, 80+ GOLD 650W (Semi Modular, EVGA ECO Mode, Power Supply, Black)",
    brand: "NsxGamers",
    price: "120",
    prevPrice: "159",
    sale: "sold out"
  },
  {
    id: 21,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "no",
    peripheral: "yes",
    category: "Mouse",
    img: `${process.env.PUBLIC_URL}/img/peripherals/0A851EBF-D545-4E1E-BDA7-CF804B2C6341.webp`,
    name: "EVGA X17 Gaming Mouse (Wired, Black, Customizable, 16,000 DPI, 5 Profiles, 10 Buttons)",
    brand: "NsxGamers",
    price: "19",
    prevPrice: "49",
    sale: "sold out"
  },
  {
    id: 22,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "no",
    peripheral: "yes",
    category: "Gaming Keyboard",
    img: `${process.env.PUBLIC_URL}/img/peripherals/6DD1554E-D8F9-47F7-B42A-BF0FD88E2724.webp`,
    name: "EVGA Z12 RGB Gaming Keyboard (RGB Backlit LED, 5 Programmable Macro Keys, Dedicated Media Keys, Water Resistant)",
    brand: "NsxGamers",
    price: "37",
    prevPrice: "59",
    sale: "sold out"
  },
  {
    id: 23,
    collection: "yes",
    gaming: "yes",
    office: "no",
    components: "no",
    peripheral: "no",
    category: "PC Gaming",
    img: `${process.env.PUBLIC_URL}/img/gaming/268340B8-2B70-491F-8D63-A11CA39C8CD3_d469a4c1-4b2b-44d1-9740-dcf9d2588d92.webp`,
    name: "Gaming PC Intel (Intel Core I5 12400F, 16 GB RAM, RTX 3060, SSD NVME of 1tb, Peripherals)",
    brand: "NsxGamers",
    price: "1235",
    prevPrice: "1435",
    sale: "sale"
  },
  {
    id: 24,
    collection: "yes",
    gaming: "yes",
    office: "no",
    components: "no",
    peripheral: "no",
    category: "PC Gaming",
    img: `${process.env.PUBLIC_URL}/img/gaming/4EAE534F-A15B-4A9A-9789-6F40AFA0F474.webp`,
    name: "GIGABYTE Gaming PC - CES 2023 - AMD Ryzen 9 7950X, GV-R69XTAORUS M-16GD G20, RAM 32G",
    brand: "NsxGamers",
    price: "4399",
    prevPrice: "5199",
    sale: "sale"
  },
  {
    id: 25,
    collection: "yes",
    gaming: "yes",
    office: "no",
    components: "no",
    peripheral: "no",
    category: "PC Gaming",
    img: `${process.env.PUBLIC_URL}/img/gaming/64E4356C-6F4A-4FC1-A446-572243BA2A37.webp`,
    name: "GIGABYTE Gaming PC - CES 2023 - INTEL CORE I9 12900K, GV-N4080AORUS M-16GD G10, RAM 32GB",
    brand: "NsxGamers",
    price: "4199",
    prevPrice: "4799",
    sale: "sale"
  },
  {
    id: 26,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "no",
    peripheral: "yes",
    category: "Headset",
    img: `${process.env.PUBLIC_URL}/img/peripherals/S37-2100921.webp`,
    name: "HEADSET MSI GAMING DS501",
    brand: "NsxGamers",
    price: "39",
    prevPrice: "79",
    sale: "sold out"
  },
  {
    id: 27,
    collection: "yes",
    gaming: "no",
    office: "yes",
    components: "no",
    peripheral: "no",
    category: "PC Office",
    img: `${process.env.PUBLIC_URL}/img/office/FC36688A-40B8-4A29-9B62-6D28536E041F.webp`,
    name: "Home & Business Desktop PC SC20 (Intel i3, 16GB RAM, HDMI, USB 3.2)",
    brand: "NsxGamers",
    price: "435",
    prevPrice: "539",
    sale: "sale"
  },
  {
    id: 28,
    collection: "yes",
    gaming: "no",
    office: "yes",
    components: "no",
    peripheral: "no",
    category: "PC Office",
    img: `${process.env.PUBLIC_URL}/img/office/6B5F8EB0-9C4B-4189-9E8E-684AD9A2B3D3.webp`,
    name: "Home & Business Desktop PC SC20 (Intel i3, 8GB RAM, HDMI, USB 3.2)",
    brand: "NsxGamers",
    price: "420",
    prevPrice: "600",
    sale: "sale"
  },
  {
    id: 29,
    collection: "yes",
    gaming: "no",
    office: "yes",
    components: "no",
    peripheral: "no",
    category: "PC Office",
    img: `${process.env.PUBLIC_URL}/img/office/6B5F8EB0-9C4B-4189-9E8E-684AD9A2B3D3.webp`,
    name: "Home & Business Desktop PC SC45 (Ryzen 5, 8GB RAM, Radeon Graphics 7, HDMI, USB 3.2)",
    brand: "NsxGamers",
    price: "506",
    prevPrice: "549",
    sale: "sale"
  },
  {
    id: 30,
    collection: "yes",
    gaming: "yes",
    office: "no",
    components: "no",
    peripheral: "no",
    category: "PC Gaming",
    img: `${process.env.PUBLIC_URL}/img/gaming/268340B8-2B70-491F-8D63-A11CA39C8CD3_d2a14014-62dc-4ea9-a1e5-34326f54ef8f.webp`,
    name: "Intel Gaming PC (Intel Core I5 12400F, 16 GB RAM, 480 GB SSD, RTX 3060, Peripherals)",
    brand: "NsxGamers",
    price: "1200",
    prevPrice: "1399",
    sale: "sale"
  },
  {
    id: 31,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/components/LD4AU008G-R3-11111.webp`,
    name: "Lexar DDR4-3200/2666 UDIMM Desktop Memory",
    brand: "NsxGamers",
    price: "34",
    prevPrice: "90",
    sale: "sale"
  },
  {
    id: 32,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/components/5940C8D2-D38A-484D-8A00-14D88EC5FDAA.webp`,
    name: "Lexar Hades RGB DDR4 3600 overclocked memory",
    brand: "NsxGamers",
    price: "114",
    prevPrice: "200",
    sale: "sale"
  },
  {
    id: 33,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/components/26F1EE6A-57E7-41A7-AD96-E94069C2052E.webp`,
    name: "LEXAR MEM SDHC 32GB 800X SDHC CLASS 10",
    brand: "NsxGamers",
    price: "18",
    prevPrice: "25",
    sale: "sale"
  },
  {
    id: 34,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/components/06F23F86-B2C2-4492-912E-76828CB7D57B.webp`,
    name: "LEXAR MEM SDHC 64GB 800X SDHC CLASS 10",
    brand: "NsxGamers",
    price: "22",
    prevPrice: "40",
    sale: "sale"
  },
  {
    id: 35,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/components/LSD1066128G.jpg`,
    name: "LEXAR MEM SDXC 128GB CLASS10-U3-V30 1066",
    brand: "NsxGamers",
    price: "37",
    prevPrice: "75",
    sale: "sold out"
  },
  {
    id: 36,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/components/LSD1066064G.webp`,
    name: "LEXAR MEM SDXC 64GB CLASS10-U3-V30 1066X",
    brand: "NsxGamers",
    price: "20",
    prevPrice: "50",
    sale: "sold out"
  },
  {
    id: 37,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/components/LNM620X512G.webp`,
    name: "LEXAR NM620 SSD M.2 512GB",
    brand: "NsxGamers",
    price: "41",
    prevPrice: "79",
    sale: "sale"
  },
  {
    id: 38,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/memory/LJDS060032G.webp`,
    name: "LEXAR PENDRIVE S60 USB 2.0 32GB BLACK",
    brand: "NsxGamers",
    price: "15",
    prevPrice: "50",
    sale: "sale"
  },
  {
    id: 39,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/memory/LJDS060064G.webp`,
    name: "LEXAR PENDRIVE S60 USB 2.0 64GB BLACK",
    brand: "NsxGamers",
    price: "19",
    prevPrice: "39",
    sale: "sale"
  },
  {
    id: 40,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/memory/LJDS080128G.webp`,
    name: "LEXAR PENDRIVE S80 USB 3.1 128GB BLACK",
    brand: "NsxGamers",
    price: "29",
    prevPrice: "59",
    sale: "sale"
  },
  {
    id: 41,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/memory/LJDS080032G.webp`,
    name: "LEXAR PENDRIVE S80 USB 3.1 32GB BLACK",
    brand: "NsxGamers",
    price: "17",
    prevPrice: "49",
    sale: "sale"
  },
  {
    id: 42,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/memory/LJDS080064G.webp`,
    name: "LEXAR PENDRIVE S80 USB 3.1 64GB BLACK",
    brand: "NsxGamers",
    price: "19",
    prevPrice: "49",
    sale: "sale"
  },
  {
    id: 43,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "RAM",
    img: `${process.env.PUBLIC_URL}/img/components/LD4BU008G-R3-1.webp`,
    name: "LEXAR RAM DDR4 16GB 3600 UDIMM RGB (8X2)",
    brand: "NsxGamers",
    price: "65",
    prevPrice: "95",
    sale: "sold out"
  },
  {
    id: 44,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "RAM",
    img: `${process.env.PUBLIC_URL}/img/components/LD4AS008G-R3.jpg`,
    name: "LEXAR RAM DDR4 8GB 3200 SODIMM",
    brand: "NsxGamers",
    price: "44",
    prevPrice: "69",
    sale: "sale"
  },
  {
    id: 45,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/memory/LSL200X001T.webp`,
    name: "LEXAR SL200 PORTABLE SSD USB 3.1 1TB",
    brand: "NsxGamers",
    price: "120",
    prevPrice: "199",
    sale: "sale"
  },
  {
    id: 46,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/memory/LSL200X512G.webp`,
    name: "LEXAR SL200 PORTABLE SSD USB 3.1 512GB",
    brand: "NsxGamers",
    price: "60",
    prevPrice: "89",
    sale: "sale"
  },
  {
    id: 47,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/memory/LNQ100X240G.webp`,
    name: "LEXAR SSD NQ100 2.5 SATA III 240GB",
    brand: "NsxGamers",
    price: "26",
    prevPrice: "59",
    sale: "sale"
  },
  {
    id: 48,
    collection: "yes",
    gaming: "yes",
    office: "no",
    components: "no",
    peripheral: "no",
    category: "PC Gaming",
    img: `${process.env.PUBLIC_URL}/img/gaming/1C069F83-24C7-4C8B-A985-6F024279D991_66ea3f82-4ade-4648-8a25-cdbda6ae9a57.webp`,
    name: "Liquid Cool Gaming PC (AMD Ryzen 7 5700x, RTX 3070, 16 GB RAM, SSD of 1tb, Peripherals, WiFi USB-C)",
    brand: "NsxGamers",
    price: "1869",
    prevPrice: "2249",
    sale: "sale"
  },
  {
    id: 49,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/memory/CMW8GX4M1E32.jpg`,
    name: "Memoria RAM Corsair (8GB DDR4-3200 VRGBP)",
    brand: "NsxGamers",
    price: "45",
    prevPrice: "89",
    sale: "sale"
  },
  {
    id: 50,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Motherboard",
    img: `${process.env.PUBLIC_URL}/img/components/779D64C8-EFFF-4C42-98C9-9058BE36BA3B.webp`,
    name: "Motherboard Asus (90MB18E0-M0E)",
    brand: "NsxGamers",
    price: "640",
    prevPrice: "799",
    sale: "sale"
  },
  {
    id: 51,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Motherboard",
    img: `${process.env.PUBLIC_URL}/img/components/90MB1BX0-M0E.webp`,
    name: "GIGABYTE Gaming PC - CES 2023 - INTEL CORE I9 12900K, GV-N4080AORUS M-16GD G10, RAM 32GB",
    brand: "NsxGamers",
    price: "665",
    prevPrice: "839",
    sale: "sale"
  },
  {
    id: 52,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Motherboard",
    img: `${process.env.PUBLIC_URL}/img/components/asus.jpg`,
    name: "Motherboard Asus (ROG STRIX X570-E GAMING WIFI II)",
    brand: "NsxGamers",
    price: "379",
    prevPrice: "439",
    sale: "sold out"
  },
  {
    id: 53,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Motherboard",
    img: `${process.env.PUBLIC_URL}/img/components/911-7D18-014.jpg`,
    name: "Motherboard MSI (PRO B560M PRO-VDH)",
    brand: "NsxGamers",
    price: "150",
    prevPrice: "199",
    sale: "sale"
  },
  {
    id: 54,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "no",
    peripheral: "yes",
    category: "Mouse",
    img: `${process.env.PUBLIC_URL}/img/peripherals/B1BA1485-3942-4FFF-B0A8-C736FE36199C.webp`,
    name: "Mouse MSI CLUTCH GM08",
    brand: "NsxGamers",
    price: "63",
    prevPrice: "74",
    sale: "sale"
  },
  {
    id: 55,
    collection: "yes",
    gaming: "yes",
    office: "no",
    components: "no",
    peripheral: "no",
    category: "PC Gaming",
    img: `${process.env.PUBLIC_URL}/img/gaming/CA8D2577-E811-464C-A01F-9220C80C871F.webp`,
    name: "MSI Gaming Computer - CES 2023 - AMD Ryzen 9 7950X, GEFORCE RTX 4080, RAM 32GB",
    brand: "NsxGamers",
    price: "3739",
    prevPrice: "4799",
    sale: "sale"
  },
  {
    id: 56,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Power supply",
    img: `${process.env.PUBLIC_URL}/img/components/100-W1-0600.jpg`,
    name: "Power supply EVGA 600W",
    brand: "NsxGamers",
    price: "115",
    prevPrice: "199",
    sale: "sale"
  },
  {
    id: 57,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Memory",
    img: `${process.env.PUBLIC_URL}/img/memory/E97C9E66-7B18-478F-AD04-2198625C4056.webp`,
    name: "GIGABYTE Gaming PC - CES 2023 - INTEL CORE I9 12900K, GV-N4080AORUS M-16GD G10, RAM 32GB",
    brand: "NsxGamers",
    price: "29",
    prevPrice: "34",
    sale: "sale"
  },
  {
    id: 58,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Gaming Graphics Card",
    img: `${process.env.PUBLIC_URL}/img/components/6413EB5B-FDF2-49CC-A0E6-49CBE4B2A660.webp`,
    name: "PowerColor Hellhound AMD Radeon RX 6600 XT Gaming Graphics Card with 8GB GDDR6 Memory, Powered by AMD RDNA 2, HDMI 2.1",
    brand: "NsxGamers",
    price: "489",
    prevPrice: "559",
    sale: "sale"
  },
  {
    id: 59,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "Power Supply",
    img: `${process.env.PUBLIC_URL}/img/components/220-P2-1200.jpg`,
    name: "PSU EVGA SuperNOVA 1200 P2 1200W, 80 PLUS Platinum, Full modular",
    brand: "NsxGamers",
    price: "265",
    prevPrice: "299",
    sale: "sold out"
  },
  {
    id: 60,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "WATERCOOLING",
    img: `${process.env.PUBLIC_URL}/img/components/306-7ZW2P11.webp`,
    name: "WATERCOOLING MSI MAG CORELIQUID P240",
    brand: "NsxGamers",
    price: "113",
    prevPrice: "159",
    sale: "sale"
  },
  {
    id: 61,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "yes",
    peripheral: "no",
    category: "RTX",
    img: `${process.env.PUBLIC_URL}/img/components/789085E9-A72B-4CE2-BCB2-A8C25D535A16.webp`,
    name: "VGA NVIDIA MSI RTX 3070 TI VENTUS 3X OC",
    brand: "NsxGamers",
    price: "765",
    prevPrice: "819",
    sale: "sale"
  },
  {
    id: 62,
    collection: "yes",
    gaming: "no",
    office: "no",
    components: "no",
    peripheral: "yes",
    category: "Keyboard",
    img: `${process.env.PUBLIC_URL}/img/peripherals/CH-9226715-N.jpg`,
    name: "TECLADO CORSAIR K55 RGB PRO XT RBRDME-PK",
    brand: "NsxGamers",
    price: "41",
    prevPrice: "59",
    sale: "sale"
  },
  {
    id: 63,
    collection: "yes",
    gaming: "yes",
    office: "no",
    components: "no",
    peripheral: "no",
    category: "PC Gaming",
    img: `${process.env.PUBLIC_URL}/img/gaming/4FD2CFF2-281D-4439-BA38-EAC0D0F4E667_5869dd26-f67e-44db-98d1-467af009868b.webp`,
    name: "Xtreme Gaming PC (AMD Ryzen 7 5700X, 16 GB RAM, RTX 3070 TI, Liquid Cooler, Peripherals)",
    brand: "NsxGamers",
    price: "1750",
    prevPrice: "2124",
    sale: "sold out"
  }
];
